/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import daos.Globale;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author formation
 */
public class JIFArrondissement extends javax.swing.JInternalFrame {

    private Connection icnx;
    private DefaultTableModel dtm;

    private JLabel[] tJLabels;
    private JTextField[] tJTexts;
    
    /**
     * Creates new form JIFArrondissement
     */
    public JIFArrondissement() {
        initComponents();
        
        icnx = Globale.getCnx();

        Object[] tEntetes = null;
        Object[][] tDataTable = null;
        Object[] tDataLigne = null;
        PreparedStatement lpst = null;
        ResultSet lrs = null;

        try {
            // --- Connexion a la BD

            lpst = icnx.prepareStatement("SELECT * FROM arrondissement", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            lrs = lpst.executeQuery();

            // --- Recuperation de la structure du curseur
            ResultSetMetaData lrsmd = lrs.getMetaData();

            // --- Nombre de colonnes du curseur
            int liColonnes = lrsmd.getColumnCount();

            // --- Noms des colonnes
            tEntetes = new Object[liColonnes];
            for (int i = 0; i < liColonnes; i++) {
                tEntetes[i] = lrsmd.getColumnName(i + 1);
            }

         // --- Pour les donnees de la JTable
            // --- Pour obtenir le nombre de lignes du curseur
            lrs.last();
            int liLignes = lrs.getRow();
            tDataTable = new Object[liLignes][liColonnes];

            lrs.beforeFirst();
            int i = 0;
            // --- Balayage des lignes
            while (lrs.next()) {
                // --- Balayage des colonnes pour construire une ligne
                tDataLigne = new Object[liColonnes];
                for (int j = 0; j < liColonnes; j++) {
                    if (lrs.getObject(j + 1) == null) {
                        tDataLigne[j] = "NUL";
                    } else {
                        tDataLigne[j] = lrs.getObject(j + 1).toString();
                    }
                }
                tDataTable[i] = tDataLigne;
                i++;
            }

            // --- Affectation des tableaux d'objets a la JTable
            dtm = new DefaultTableModel(tDataTable, tEntetes);
            jTableArrondissement.setModel(dtm);

            // Fermetures
            lrs.close();
            lpst.close();
            
            
            
            /*
            Dyn des labels et des JtextFields
            */
            int iiPosX = 0;
            int iiPosY = 0;
            
            tJLabels = new JLabel[tEntetes.length];
            tJTexts = new JTextField[tEntetes.length];
            
            for(i = 0; i < tJLabels.length; i++) {
                tJLabels[i] = new JLabel(tEntetes[i].toString());
                tJTexts[i] = new JTextField();
                
                jPanel1.add(tJLabels[i]);
                
                tJLabels[i].setSize(200, 30);
                tJLabels[i].setLocation(iiPosX + 10, iiPosY);
                tJLabels[i].setVisible(true);
                
                jPanel1.add(tJTexts[i]);
                tJTexts[i].setSize(150, 30);
                tJTexts[i].setLocation(iiPosX + 200, iiPosY);
                iiPosY += 30;
            }
            
            

        } /// du try
        catch (SQLException e) {
            jLabelMessage.setText(e.getMessage());
        }
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArrondissement = new javax.swing.JTable();
        jLabelMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Arrondissement");

        jTableArrondissement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableArrondissement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableArrondissementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableArrondissement);

        jLabelMessage.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMessage)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabelMessage)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableArrondissementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableArrondissementMouseClicked
        // TODO add your handling code here:
        int liRow = jTableArrondissement.getSelectedRow();
        for(int i = 0; i < jTableArrondissement.getColumnCount(); i++) {
            tJTexts[i].setText(jTableArrondissement.getValueAt(liRow, i).toString());
        }
    }//GEN-LAST:event_jTableArrondissementMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableArrondissement;
    // End of variables declaration//GEN-END:variables
}
