/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import daos.GenreDAO;
import daos.Globale;
import entities.Genre;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author formation
 */
public class JIFGenre extends javax.swing.JInternalFrame {

    private final Connection icnx;
    private final DefaultTableModel ldtm;
    private final GenreDAO dao;

    /**
     * Creates new form JIFGenre
     */
    public JIFGenre() {
        initComponents();

        ldtm = (DefaultTableModel) jTableGenre.getModel();

        icnx = Globale.getCnx();
        Object[] tLigne = new Object[4];
        // Récupérer tous les départements
        dao = new GenreDAO(icnx);
        List<Genre> result = dao.selectAll();
        for (Genre rs : result) {
            tLigne[0] = rs.getIdGenre();
            tLigne[1] = rs.getCodeGenre();
            tLigne[2] = rs.getLibelleGenre();
            tLigne[3] = rs.getGenreGrammatical();
            
            ldtm.addRow(tLigne);
        }

        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGenre = new javax.swing.JTable();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldLibelle = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCLS = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonInsert = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldGenreGrammatical = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CRUD Genre");

        jTableGenre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Genre", "Code Genre", "Libelle Genre", "Genre Grammatical"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGenre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGenreMouseClicked(evt);
            }
        });
        jTableGenre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableGenreKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableGenre);

        jButtonDelete.setText("Supprimer");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelID.setBackground(new java.awt.Color(255, 51, 51));
        jLabelID.setForeground(new java.awt.Color(255, 0, 51));

        jLabel1.setText("ID");

        jLabel2.setText("Code Genre");

        jLabel3.setText("Libelle genre");

        jButtonCLS.setText("CLS");
        jButtonCLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLSActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Modifier");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonInsert.setText("Ajouter");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jLabel4.setText("Genre Grammatical");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCLS)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInsert)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldGenreGrammatical, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldGenreGrammatical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCLS)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonInsert)
                    .addComponent(jButtonDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableGenreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGenreMouseClicked
        // TODO add your handling code here:
        int liRow = jTableGenre.getSelectedRow();
        for (int i = 0; i < jTableGenre.getColumnCount(); i++) {
            jLabelID.setText(jTableGenre.getValueAt(liRow, 0).toString());
            jTextFieldCode.setText(jTableGenre.getValueAt(liRow, 1).toString());
            jTextFieldLibelle.setText(jTableGenre.getValueAt(liRow, 2).toString());
            jTextFieldGenreGrammatical.setText(jTableGenre.getValueAt(liRow, 3).toString());
        }
    }//GEN-LAST:event_jTableGenreMouseClicked

    private void jTableGenreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableGenreKeyReleased
        // TODO add your handling code here:
        jTableGenreMouseClicked(null);
    }//GEN-LAST:event_jTableGenreKeyReleased

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int id;
        id = Integer.valueOf(jLabelID.getText().toString());
        Genre d = new Genre(id, jTextFieldCode.getText().toString(),
                jTextFieldLibelle.getText().toString(), jTextFieldGenreGrammatical.getText().toString());

        int r = dao.delete(d);
        if (r > 0) {
            try {
                // Validation de l'exécution
                icnx.commit();
                // Maj de la jTableGenre
                int liRow = jTableGenre.getSelectedRow();
                ldtm.removeRow(liRow);

                jButtonCLSActionPerformed(null);

            } catch (SQLException e) {
                System.out.println("Del + lose : " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLSActionPerformed
        // TODO add your handling code here:
        jLabelID.setText(null);
        jTextFieldCode.setText(null);
        jTextFieldLibelle.setText(null);
        jTextFieldGenreGrammatical.setText(null);
    }//GEN-LAST:event_jButtonCLSActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        int id;
        id = Integer.valueOf(jLabelID.getText().toString());

        Genre d = new Genre(id, jTextFieldCode.getText().toString(),
                jTextFieldLibelle.getText().toString(),
                jTextFieldGenreGrammatical.getText().toString());

        int r = dao.update(d);
        if (r > 0) {
            try {
                // Valider l'exécution
                icnx.commit();
                // Maj du tableau
                int liRow = jTableGenre.getSelectedRow();
                jTableGenre.setValueAt(jTextFieldCode.getText().toString(), liRow, 1);
                jTableGenre.setValueAt(jTextFieldLibelle.getText().toString(), liRow, 2);
                jTableGenre.setValueAt(jTextFieldGenreGrammatical.getText().toString(), liRow, 3);

                jButtonCLSActionPerformed(null);

            } catch (SQLException e) {
                System.out.println("Ins + lose : " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        // TODO add your handling code here:
        Genre d = new Genre(jTextFieldCode.getText().toString(),
                jTextFieldLibelle.getText().toString(), jTextFieldGenreGrammatical.getText().toString());

        int r = dao.insert(d);
        if (r > 0) {
            try {
                // Valider l'exécution
                icnx.commit();
                // Maj du tableau (jDableGenre)
                Object[] tLigne = new Object[4];
                tLigne[0] = r;
                tLigne[1] = jTextFieldCode.getText().toString();
                tLigne[2] = jTextFieldLibelle.getText().toString();
                tLigne[3] = jTextFieldGenreGrammatical.getText().toString();
                
                ldtm.addRow(tLigne);

                jButtonCLSActionPerformed(null);

            } catch (SQLException e) {
                System.out.println("Ins + lose : " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonInsertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCLS;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGenre;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldGenreGrammatical;
    private javax.swing.JTextField jTextFieldLibelle;
    // End of variables declaration//GEN-END:variables
}
