/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package boundaries;

import bdd.paysModel;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author formation
 */
public class JIFPaysModification extends javax.swing.JInternalFrame {

    private DefaultComboBoxModel idcbm;
    private Map mapCountry;

    /**
     * Creates new form JIFPaysModification
     */
    public JIFPaysModification() {
        initComponents();
        idcbm = new DefaultComboBoxModel();
        paysModel pays = new paysModel();
        Set<String> keyAllCountries;
        
        mapCountry = pays.getData();
        
        keyAllCountries = mapCountry.keySet();
        keyAllCountries.stream().forEach((lr) -> {
            idcbm.addElement(lr);
        });
        
        jComboBoxPays.setModel(idcbm);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxPays = new javax.swing.JComboBox();
        jButtonValiderChoix = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonValiderModification = new javax.swing.JButton();
        jTextFieldNomPays = new javax.swing.JTextField();
        jTextFieldNomMasculin = new javax.swing.JTextField();
        jTextFieldFeminin = new javax.swing.JTextField();
        jTextFieldNomNeutre = new javax.swing.JTextField();
        jLabelMessage = new javax.swing.JLabel();
        jTextFieldIDPays = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pays Modification");

        jLabel1.setText("Pays à modifier ?");

        jButtonValiderChoix.setText("Valider");
        jButtonValiderChoix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderChoixActionPerformed(evt);
            }
        });

        jLabel2.setText("ID pays");

        jLabel3.setText("Nom du pays");

        jLabel4.setText("masculin");

        jLabel5.setText("Féminin");

        jLabel6.setText("Neutre");

        jButtonValiderModification.setText("Valider la modification");
        jButtonValiderModification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderModificationActionPerformed(evt);
            }
        });

        jLabelMessage.setText("Message");

        jTextFieldIDPays.setEditable(false);
        jTextFieldIDPays.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonValiderChoix))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldNomPays)
                                            .addComponent(jTextFieldNomMasculin)
                                            .addComponent(jTextFieldFeminin)
                                            .addComponent(jTextFieldNomNeutre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldIDPays, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButtonValiderModification, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonValiderChoix))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIDPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNomPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNomMasculin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldFeminin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNomNeutre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonValiderModification)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderChoixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderChoixActionPerformed
        // TODO add your handling code here:
        paysModel pays = new paysModel();
        Map<String, String> mapSelectedCountry;
        String id = (String) mapCountry.get(jComboBoxPays.getSelectedItem().toString());
        mapSelectedCountry = pays.getOneData(id);

//        for (Map.Entry<String, String> entry : mapSelectedCountry.entrySet()) {
//            String string = entry.getKey();
//            String string1 = entry.getValue();
//            System.out.println(string + ":" + string1);           
//        }
        jTextFieldIDPays.setText(mapSelectedCountry.get("ID_pays").toString());
        jTextFieldNomPays.setText(mapSelectedCountry.get("Nom_pays").toString());
        jTextFieldNomMasculin.setText(mapSelectedCountry.get("MASCULIN").toString());
        jTextFieldFeminin.setText(mapSelectedCountry.get("FEMININ").toString());
        jTextFieldNomNeutre.setText(mapSelectedCountry.get("Neutre").toString());
    }//GEN-LAST:event_jButtonValiderChoixActionPerformed

    private void jButtonValiderModificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderModificationActionPerformed
        // TODO add your handling code here:
        paysModel pays = new paysModel();
        String id = (String) mapCountry.get(jComboBoxPays.getSelectedItem().toString());
        if (jTextFieldNomPays.getText().isEmpty() || jTextFieldNomMasculin.getText().isEmpty()
                || jTextFieldFeminin.getText().isEmpty() || jTextFieldNomNeutre.getText().isEmpty()) {
            jLabelMessage.setText("Tous les champs sont obligatoires");
        } else {
            pays.updateData(id, jTextFieldNomPays.getText().toString(), jTextFieldNomMasculin.getText().toString(),
                    jTextFieldFeminin.getText().toString(), jTextFieldNomNeutre.getText().toString()); 
            jLabelMessage.setText("Votre modification a été enregistrée");            
        }
        
    }//GEN-LAST:event_jButtonValiderModificationActionPerformed
    
    private void resetFields() {
        jTextFieldIDPays.setText(null);
        jTextFieldNomPays.setText(null);
        jTextFieldNomMasculin.setText(null);
        jTextFieldFeminin.setText(null);
        jTextFieldNomNeutre.setText(null);        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValiderChoix;
    private javax.swing.JButton jButtonValiderModification;
    private javax.swing.JComboBox jComboBoxPays;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JTextField jTextFieldFeminin;
    private javax.swing.JTextField jTextFieldIDPays;
    private javax.swing.JTextField jTextFieldNomMasculin;
    private javax.swing.JTextField jTextFieldNomNeutre;
    private javax.swing.JTextField jTextFieldNomPays;
    // End of variables declaration//GEN-END:variables
}
