/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import bdd.paysModel;
import daos.Globale;
import daos.PaysDAO;
import entities.Pays;
import java.sql.*;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author formation
 */
public class JIFPaysVisu extends javax.swing.JInternalFrame {
private Connection icnx;
    /**
     * Creates new form JIFPaysVisu
     */
    public JIFPaysVisu() {
        initComponents();

        Object[] tLigne = new Object[5];
        DefaultTableModel ldtm = (DefaultTableModel) jTablePays.getModel();

        icnx = Globale.getCnx();
        PaysDAO dao = new PaysDAO(icnx);
        
        List<Pays> p = dao.selectAll();
        for(Pays rs:p){
            tLigne[0] = rs.getIdPays();
            tLigne[1] = rs.getNomPays();
            tLigne[2] = rs.getMasculin();
            tLigne[3] = rs.getFeminin();
            tLigne[4] = rs.getNeutre();
            ldtm.addRow(tLigne);
        }
//        paysModel pays = new paysModel();
//        List<Map<String, String>> listCountries = pays.getAllData();
//        for (int i = 0; i < listCountries.size(); i++) {
//            tLigne = new Object[5];
//            Map<String, String> mapCountry = listCountries.get(i);
//
//            tLigne[0] = mapCountry.get("ID_pays");
//            tLigne[1] = mapCountry.get("NOM_pays");
//            tLigne[2] = mapCountry.get("MASCULIN");
//            tLigne[3] = mapCountry.get("FEMININ");
//            tLigne[4] = mapCountry.get("NEUTRE");
//
//            ldtm.addRow(tLigne);
//        }
        
        jLabelMessage.setText("il y'a " + p.size() + " pays ");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePays = new javax.swing.JTable();
        jLabelMessage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Visualisation Pays");

        jTablePays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pays", "Nom du pays", "Masculin", "Féminin", "Neutre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePays);

        jLabelMessage.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMessage)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePays;
    // End of variables declaration//GEN-END:variables
}
